services:
  mysql:
    image: mysql:8.0
    container_name: project-blog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project_blog
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: project-blog-backend
    restart: always
    volumes:
      - ./backend:/var/www
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: project_blog
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    depends_on:
      - mysql
    command: php-fpm

  nginx:
    image: nginx:stable
    container_name: project-blog-nginx
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: project-blog-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
